# Plugin: jQuiz
# Desenvolvido por: Jaao
# Twitter: @_jaoraphael

# Permissões
# jquiz.player | Permissões de player
# jquiz.admin | Permissões de player + permissões de admin


# Quiz
# Aqui são salvas as informações sobre o quiz atual, não altere para que não haja erros.

aberto: false
pergunta: 'padrao-a'
resposta: 'padrao-a'

# Opções

firework: true
title: true
msg_chat: true
money: true
money_quantidade: 3000


# Mensagens

configuracao_recarregada: "&a[jQuiz] Configuração recarregada."
quiz_aberto:
  - ''
  - '&6  Há um quiz aberto no momento.'
  - '&6  Pergunta: &e{pergunta}'
  - '&6  Utilize o comando /quiz responder (resposta)'
  - '&6  para responder.'
  - ''
anuncios_automaticos:
  - ''
  - '&6[Quiz] &eEvento aberto!'
  - '&6[Quiz] &ePergunta: {pergunta}'
  - '&6[Quiz] &ePara responder utilize o comando'
  - '&6[Quiz] &e/quiz responder (sua resposta)'
  - '&6[Quiz] &eChamados restantes: {chamados}'
  - ''
quiz_fechado: '&cNão há nenhum quiz aberto no momento. Utilize /quiz help para mais informações.'
ajuda_player:
  - ''
  - '&6Quiz é o nome de um jogo de questionários que tem como objetivo fazer uma avaliação dos conhecimentos sobre determinado assunto. Neste tipo de jogo podem participar tanto grupo de muitas pessoas, como participantes individuais, que devem acertar a maior quantidade de respostas para ganhar.'
  - ''
  - '&eNa modificação feita para o nosso servidor o Quiz é um evento que pode ser iniciado a qualquer momento pela staff e o player que responder primeiro corretamente a pergunta, ganha uma quantia de money.'
  - ''
ajuda_admin:
  - ''
  - '&6&lComandos'
  - '&e -/quiz help * Ajuda do plugin'
  - '&e -/quiz dev * Informações sobre o plugin'
  - '&e -/quiz iniciar (pergunta) * Inicia o quiz'
  - '&e -/quiz resposta (resposta) * Define a resposta'
  - '&e -/quiz cancelar * Cancela o quiz'
  - ''
cancelado:
  - ''
  - '&6[Quiz] &eEvento cancelado!'
  - ''
cancelado: '&cQuiz cancelado com sucesso!'
cancelado_fechado: '&cNão há nenhum quiz aberto no momento.'
ja_aberto: '&cJá há um quiz aberto, cancele-o ou aguarde o término para iniciar outro.'
def_resposta: '&eAgora é necessário definir uma resposta, utilize o comando &6/quiz resposta (resposta)&e.'
ja_def_resposta: '&cA resposta já foi definida.'
naoha_pergunta: '&cÉ necessário definir uma pergunta primeiro.'
resp_def: '&eResposta definidada para: &7{resposta}'
admin_nresp: '&cAdministradores não podem responder perguntas do quiz.'
fechado_resp: '&cNão há nenhum quiz aberto no momento.'
resp_erro: '&cResposta errada! Tente novamente.'
premio_depos: '&a{quantia}c foram adicionados a sua conta.'
iniciado: 
  - ''
  - '&6[Quiz] &eEvento iniciado!'
  - '&6[Quiz] &ePergunta: {pergunta}'
  - '&6[Quiz] &ePara responder utilize o comando'
  - '&6[Quiz] &e/quiz responder (sua resposta)'
  - ''
finalizado:
  - ''
  - '&6[Quiz] &eGanhador: {ganhador}'
  - '&6[Quiz] &eResposta: {resposta}'
  - ''
cancelado_part:
  - ''
  - '&6[Quiz] Ninguém acertou a resposta e o evento foi cancelado.'
  - ''
title_finalizado:
  title: '&6[Quiz]'
  subtitle: '&e{player} ganhou!'